# Default values for 5gcore-helm.

open5gcore:
  image:
    repository: docker.io/efatnar/open5gcore
    pullPolicy: IfNotPresent
    tag: "v1.1"

webui:
  image:
    repository: docker.io/efatnar/open5gcore-webui
    pullPolicy: IfNotPresent
    tag: "v1.1"

dnn: internet  

amf:
  mcc: 208
  mnc: 93
  tac: 7

smf:
  # when distributed, this should use the *-shared service so NRF can reach back through skupper
  serviceName: open5gs-smf #open5gs-smf-shared

nrf:
  # the distributed component should use the *-shared service, as it will be exposed through skupper
  serviceName: open5gs-nrf #open5gs-nrf-shared

k8s:
 interface: eth0
 
