---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: 5g-core-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          5g-core: "True"
