kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: 5gpolicy
  namespace: open5gcore
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector: {}
  policyTypes:
    - Ingress
