{{ if .Values.ausf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    ausf:
      sbi:
      - dev: {{ .Values.k8s.interface }}
        advertise: open5gs-ausf.{{ .Release.Namespace }}.svc.cluster.local
    nrf:
     sbi:
      name: open5gs-nrf
{{ end }}