{{ if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb-d
  annotations:
    skupper.io/proxy: tcp
    skupper.io/address: open5gs-mongodb-shared
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      initContainers:
      - name: init-mydb
        image: registry.access.redhat.com/ubi8/ubi:latest
        command: ['sh', '-c', 'cd /data/db && curl https://raw.githubusercontent.com/open5gs/open5gs/v2.6.4/docs/assets/webui/mongo-init.js;']
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      containers:
      - image: quay.io/adetalho/free5gmano-mongodb
        name: open5gs-mongodb
        command: ["/bin/sh"]
        args: ["-c", "mongod; sleep 5; mongo open5gs ./data/db/user-init.js"]
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{ end }}