{{ if .Values.nssf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf
  annotations:
    skupper.io/proxy: http2
    skupper.io/address: open5gs-nssf-shared
  labels:
    epc-mode: nssf
spec:
  selector:
    epc-mode: nssf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nssf-d
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: nssf
    spec:   
      containers:
        - name: nssf
          image: "{{ .Values.open5gcore.image.repository }}:{{ .Values.open5gcore.image.tag }}"
          imagePullPolicy: {{ .Values.open5gcore.image.pullPolicy }}
          securityContext:
            privileged: true
          command: ["open5gs-nssfd", "-d", "-c", "/open5gs/config-map/nssf.yaml"]
          volumeMounts:
          - name: open5gs-nssf-config
            mountPath: /open5gs/config-map/nssf.yaml
            subPath: "nssf.yaml"          
      volumes:
        - name: open5gs-nssf-config
          configMap:
            name: open5gs-nssf-config           
{{ end }}
