kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-open5gcore
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-admin-role
  namespace: open5gcore 
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - scc-open5gcore
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scc-admin-rolebinding
  namespace: open5gcore
subjects:
  - kind: ServiceAccount
    name: default
    namespace: open5gcore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-admin-role
