{{ if .Values.udm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    #logger:
      #file: /var/log/open5gs/udm.log
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true
    udm:
      sbi:   
      - addr: 0.0.0.0
        advertise: {{ .Values.udm.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
    nrf:
     sbi:
      name: {{ .Values.nrf.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}