# Default values for 5gcore-helm.

open5gcore:
  image:
    repository: quay.io/adetalho/open5gs
    pullPolicy: Always
    tag: "v2.6.4"

webui:
  enabled: true
  image:
    repository: quay.io/adetalho/open5gs-webui 
    pullPolicy: IfNotPresent
    tag: "v2.6.4"

dnn: internet  

k8s:
 interface: eth0

amf:
  enabled: true
  mcc: 208
  mnc: 93
  tac: 7
  serviceName: open5gs-amf
bsf:
  enabled: true
ausf:
  enabled: true
mongo:
  enabled: true
nrf:
  enabled: true
  serviceName: open5gs-nrf
nssf:
  enabled: true
pcf:
  enabled: true
  serviceName: open5gs-pcf
udm:
  enabled: true
  serviceName: open5gs-udm
udr:
  enabled: true
upf:
  enabled: false
  pfcpServiceName: open5gs-upf-pfcp-shared
smf:
  enabled: true
  pfcpServiceName: open5gs-smf-pfcp-shared
  serviceName: open5gs-smf
